#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/nf_type.h"
#include "../model/options_response.h"
#include "../model/problem_details.h"
#include "../model/redirect_response.h"
#include "../model/uri_list.h"

// Enum  for NFInstancesStoreAPI_getNFInstances
typedef enum  { nrf_nfmanagement_service_getNFInstances__NULL = 0, nrf_nfmanagement_service_getNFInstances__NRF, nrf_nfmanagement_service_getNFInstances__UDM, nrf_nfmanagement_service_getNFInstances__AMF, nrf_nfmanagement_service_getNFInstances__SMF, nrf_nfmanagement_service_getNFInstances__AUSF, nrf_nfmanagement_service_getNFInstances__NEF, nrf_nfmanagement_service_getNFInstances__PCF, nrf_nfmanagement_service_getNFInstances__SMSF, nrf_nfmanagement_service_getNFInstances__NSSF, nrf_nfmanagement_service_getNFInstances__UDR, nrf_nfmanagement_service_getNFInstances__LMF, nrf_nfmanagement_service_getNFInstances__GMLC, nrf_nfmanagement_service_getNFInstances__5G_EIR, nrf_nfmanagement_service_getNFInstances__SEPP, nrf_nfmanagement_service_getNFInstances__UPF, nrf_nfmanagement_service_getNFInstances__N3IWF, nrf_nfmanagement_service_getNFInstances__AF, nrf_nfmanagement_service_getNFInstances__UDSF, nrf_nfmanagement_service_getNFInstances__BSF, nrf_nfmanagement_service_getNFInstances__CHF, nrf_nfmanagement_service_getNFInstances__NWDAF, nrf_nfmanagement_service_getNFInstances__PCSCF, nrf_nfmanagement_service_getNFInstances__CBCF, nrf_nfmanagement_service_getNFInstances__HSS, nrf_nfmanagement_service_getNFInstances__UCMF, nrf_nfmanagement_service_getNFInstances__SOR_AF, nrf_nfmanagement_service_getNFInstances__SPAF, nrf_nfmanagement_service_getNFInstances__MME, nrf_nfmanagement_service_getNFInstances__SCSAS, nrf_nfmanagement_service_getNFInstances__SCEF, nrf_nfmanagement_service_getNFInstances__SCP, nrf_nfmanagement_service_getNFInstances__NSSAAF, nrf_nfmanagement_service_getNFInstances__ICSCF, nrf_nfmanagement_service_getNFInstances__SCSCF, nrf_nfmanagement_service_getNFInstances__DRA, nrf_nfmanagement_service_getNFInstances__IMS_AS, nrf_nfmanagement_service_getNFInstances__AANF, nrf_nfmanagement_service_getNFInstances___5G_DDNMF, nrf_nfmanagement_service_getNFInstances__NSACF, nrf_nfmanagement_service_getNFInstances__MFAF, nrf_nfmanagement_service_getNFInstances__EASDF, nrf_nfmanagement_service_getNFInstances__DCCF, nrf_nfmanagement_service_getNFInstances__MB_SMF, nrf_nfmanagement_service_getNFInstances__TSCTSF, nrf_nfmanagement_service_getNFInstances__ADRF, nrf_nfmanagement_service_getNFInstances__GBA_BSF, nrf_nfmanagement_service_getNFInstances__CEF, nrf_nfmanagement_service_getNFInstances__MB_UPF, nrf_nfmanagement_service_getNFInstances__NSWOF, nrf_nfmanagement_service_getNFInstances__PKMF, nrf_nfmanagement_service_getNFInstances__MNPF, nrf_nfmanagement_service_getNFInstances__SMS_GMSC, nrf_nfmanagement_service_getNFInstances__SMS_IWMSC, nrf_nfmanagement_service_getNFInstances__MBSF, nrf_nfmanagement_service_getNFInstances__MBSTF, nrf_nfmanagement_service_getNFInstances__PANF } nrf_nfmanagement_service_getNFInstances_nf-type_e;


// Retrieves a collection of NF Instances
//
uri_list_t*
NFInstancesStoreAPI_getNFInstances(apiClient_t *apiClient, nf_type_e nf_type , int limit , int page_number , int page_size );


// Discover communication options supported by NRF for NF Instances
//
options_response_t*
NFInstancesStoreAPI_optionsNFInstances(apiClient_t *apiClient);


